services:
  - type: web
    name: the-league-api
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
      - key: Mongo__ConnectionString
        sync: false
      - key: Mongo__DatabaseName
        value: the-league
      - key: Cors__AllowedOrigins__0
        sync: false
